//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cityGraph
    {
        public int Id { get; set; }
        public string sehir_adi { get; set; }
        public Nullable<int> sehir_veri_1 { get; set; }
        public Nullable<int> sehir_veri_2 { get; set; }
        public Nullable<int> sehir_veri_3 { get; set; }
    }
}
